version: '3.7'

services:
  api:
    container_name:  "explorador_api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile
     
    ports:
      - 8282:8080
    restart: on-failure
    
    # we are depending on the mysql backend
    depends_on:
      - fullstack-mysql          
    networks:
      - fullstack

    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/
 
  fullstack-mysql:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 33066:33066
    environment: 
      - MYSQL_ROOT_HOST=fullstack-mysql
      - MYSQL_USER=steven
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=fullstack_api
      - MYSQL_ROOT_PASSWORD=12345678
      
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
  
volumes:
  api:
  #database_postgres_test:
  database_mysql:
networks:
  fullstack:
    driver: bridge