package constantvariables

const NAVIGANTORS_ROL = 6
const PIONEERS_ROL = 26
const PATH_FOLLOWERS_ROL = 27
const SCOUTS_ROL = 28

const FIRST_MAJOR_ROL = 2
const SECOND_MAJOR_ROL = 3
const FIRST_COMMANDERS_ROL = 4
const SECOND_COMMANDERS_ROL = 5

const CHAN_VALUE = 1
const KING_SCOUTS = 29

const NAVIGANTORS_SUB_DETACHMENT = 1
const PIONEERS_SUB_DETACHMENT = 2
const PATH_FOLLOWERS_SUB_DETACHMENT = 3
const SCOUTS_SUB_DETACHMENT = 4
const OPTION_CREATE = 1
const OPTION_EDIT = 2
